namePrefix: cricket-
commonLabels:
  infra: docker
resources:
- namespace.yaml
- calico.yaml
bases:
- ../../../docker
namespace: cricket
patchesStrategicMerge:
- healthCheck.yaml
- cluster.yaml
- clusterClass.yaml
